name: TurnersAPI - Cloud Functions Deploy

on:
    push:
        branches:
            - main
        paths:
            - index.js
            - src/controllers/controllers.js
            - src/test/test.spec.js
            - .github/workflows/gCloudDeploy.yml

jobs:
    deploy:
        name: Deploy to Google Cloud Functions
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Authenticate to Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: tavares-mission-3

            - name: Deploy Cloud Functions
              run: |
                  gcloud functions deploy turnersAPI \
                  --entry-point turnersAPI \
                  --runtime nodejs20 \
                  --trigger-http \
                  --project tavares-mission-3

    unit-test:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '18'
            - run: npm install
            - run: npm test
